const CERTIFICATIONS = [
  "aws certified solutions architect",
  "aws certified developer",
  "aws certified sysops administrator",
  "google certified professional cloud architect",
  "google certified data engineer",
  "microsoft certified: azure solutions architect",
  "microsoft certified: azure administrator",
  "microsoft certified: azure security engineer",
  "adobe certified expert",
  "google ux design professional certificate",
  "comptia a+",
  "comptia network+",
  "comptia security+",
  "comptia cloud+",
  "cisco certified network associate (ccna)",
  "cisco certified network professional (ccnp)",
  "cisco certified internetwork expert (ccie)",
  "oracle certified professional (ocp)",
  "oracle certified associate (oca)",
  "python institute - pcep",
  "python institute - pcap",
  "red hat certified engineer (rhce)",
  "red hat certified system administrator (rhcsa)",
  "certified kubernetes administrator (cka)",
  "certified ethical hacker (ceh)",
  "offensive security certified professional (oscp)",
  "isc2 certified information systems security professional (cissp)",
  "isaca certified information security manager (cism)",
  "isaca certified information systems auditor (cisa)",
  "google associate android developer",
  "google professional machine learning engineer",
  "scrum master certified (smc)",
  "professional scrum master (psm)",
  "itil foundation certification",

  "chartered financial analyst (cfa)",
  "certified public accountant (cpa)",
  "financial risk manager (frm)",
  "chartered insurance specialist (cis)",
  "chartered investment manager (cim)",
  "chartered alternative investment analyst (caia)",
  "accredited management accountant (ama)",

  "project management professional (pmp)",
  "prince2 certification",
  "six sigma green belt",
  "six sigma black belt",
  "certified business analyst professional (cbap)",
  "lean six sigma certification",
  "business process management professional (bpmp)",

  "google ads certification",
  "hubspot inbound marketing certification",
  "facebook blueprint certification",
  "digital marketing institute certification",

  "licensed real estate broker (lreb)",
  "certified property manager (cpm)",

  "professional in human resources (phr)",
  "senior professional in human resources (sphr)",

  "basic life support (bls)",
  "advanced cardiac life support (acls)",
  "certified nursing assistant (cna)",
  "registered nurse (rn)",
  "board certified behavior analyst (bcba)",

  "ielts",
  "toefl",
  "toeic",
  "jlpt n1",
  "jlpt n2",
  "topik ii",
  "delf b2",
  "goethe zertifikat b2",
];

export default CERTIFICATIONS;
