const COMPANIES = [
  "aws (amazon web services)",
  "microsoft",
  "google",
  "freelance",
  "rmit university vietnam (rmit)",
  "vintech (vingroup)",
  "fpt corporation",
  "viettel group",
  "mobifone",
  "samsung vietnam",
  "vnpt",
  "vng corporation",
  "cmc corporation",
  "tinhvan group",
  "rikkeisoft",
  "tma solutions",
  "nashtech vietnam",
  "tof software",
  "kms technology",
  "sutrix solutions",
  "arentfox software",
  "orient software",
  "amela technology",
  "hcl vietnam",
  "deliveree vietnam",
  "axon active vietnam",
  "lg electronics vietnam",
  "viet software international (vsii)",
  "global cybersoft vietnam",
  "bravo software",
  "evotek jsc",
  "techbase vietnam",
  "tiki corporation",
  "shopee vietnam",
  "lazada vietnam",
  "gojek vietnam",
  "grab vietnam",
  "be group (be vietnam)",
  "vietcombank",
  "agribank",
  "bidv",
  "techcombank",
  "vietinbank",
  "vpbank",
  "sacombank",
  "mb bank",
  "acb",
  "ocb",
  "hdbank",
  "shinhan bank vietnam",
  "uob vietnam",
  "tpbank",
  "fe credit",
  "mirae asset finance vietnam",
  "vietcredit",
  "retail & e-commerce",
  "vincommerce (winmart)",
  "the gioi di dong (mobile world)",
  "dien may xanh",
  "fpt shop",
  "lotte mart vietnam",
  "big c vietnam (go!)",
  "circle k vietnam",
  "7-eleven vietnam",
  "manufacturing & industry",
  "hoa phat group",
  "vinfast",
  "samsung electronics vietnam",
  "canon vietnam",
  "intel vietnam",
  "panasonic vietnam",
  "bosch vietnam",
  "mitsubishi vietnam",
  "siemens vietnam",
  "doosan vina",
  "real estate & construction",
  "vingroup",
  "sun group",
  "novaland group",
  "dat xanh group",
  "khang dien house",
  "hung thinh corporation",
  "phat dat real estate",
  "ecopark",
  "nam long group",
  "logistics & transportation",
  "vietnam airlines",
  "vietjet air",
  "bamboo airways",
  "vina express",
  "vnpost",
  "ghn express",
  "viettel post",
  "best express vietnam",
  "j&t express vietnam",
];

export default COMPANIES;
