enum ROLES {
  ADMIN = "ADMIN",
  MENTOR = "MENTOR",
  STUDENT = "STUDENT",
}

enum GENDERS {
  MALE = "MALE",
  FEMALE = "FEMALE",
  OTHER = "OTHER",
}

enum ACHIEVEMENT_TYPES {
  EDUCATION = "EDUCATION",
  EXPERIENCE = "EXPERIENCE",
  CERTIFICATION = "CERTIFICATION",
}

enum EDUCATION_LEVELS {
  PRIMARY = "PRIMARY",
  SECONDARY = "SECONDARY",
  HIGH_SCHOOL = "HIGH_SCHOOL",
  UNIVERSITY = "UNIVERSITY",
}

enum MENTOR_STATUS {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
}

enum MEETING_STATUS {
  SCHEDULED = "SCHEDULED",
  ONGOING = "ONGOING",
  FINISHED = "FINISHED",
  CANCELLED = "CANCELLED",
}

enum MEETING_TYPE {
  DEFAULT = "DEFAULT",
  AUDIOROOM = "AUDIOROOM",
  LIVESTREAMING = "LIVESTREAMING",
}

enum PARTICIPANT_ROLE {
  ADMIN = "ADMIN",
  USER = "USER",
}

enum RESOURCE_TYPE {
  IMAGE = "IMAGE",
  RAW = "RAW",
  VIDEO = "VIDEO",
}

enum FOLDER {
  IMAGES = "IMAGES",
  VIDEOS = "VIDEOS",
  FILES = "FILES",
}

enum TARGET_AUDIENCE {
  BEGINNER = "BEGINNER",
  INTERMEDIATE = "INTERMEDIATE",
  ADVANCED = "ADVANCED",
  EXPERT = "EXPERT",
}

enum COURSE_TYPE {
  PROGRAM = "PROGRAM",
  SINGLE_EVENT = "SINGLE_EVENT",
}

enum COURSE_STATUS {
  DRAFT = "DRAFT",
  PENDING = "PENDING",
  STOPPED = "STOPPED",
  ARCHIVED = "ARCHIVED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export {
  ROLES,
  GENDERS,
  ACHIEVEMENT_TYPES,
  EDUCATION_LEVELS,
  MENTOR_STATUS,
  MEETING_STATUS,
  MEETING_TYPE,
  PARTICIPANT_ROLE,
  RESOURCE_TYPE,
  FOLDER,
  TARGET_AUDIENCE,
  COURSE_TYPE,
  COURSE_STATUS,
};
