const MAJORS = [
  "information technology",
  "software engineering",
  "computer science",
  "network engineering",
  "cyber security",
  "data science",
  "artificial intelligence",
  "machine learning",
  "big data analytics",
  "cloud computing",
  "blockchain technology",
  "robotics",
  "game development",
  "mobile application development",
  "information system",
  "business information system",
  "business analytics",
  "computer engineering",
  "software testing",
  "devops engineering",
  "business administration",
  "international business",
  "entrepreneurship",
  "supply chain management",
  "logistics and transportation",
  "digital marketing",
  "brand management",
  "sales management",
  "consumer behavior",
  "advertising",
  "finance",
  "banking",
  "mathematics",
  "investment banking",
  "financial engineering",
  "accounting",
  "auditing",
  "taxation",
  "economic policy",
  "econometrics",
  "statistics",
  "actuarial science",
  "human resource management",
  "organizational behavior",
  "labor relations",
  "hospitality management",
  "tourism management",
  "event management",
  "hotel management",
  "restaurant management",
  "culinary arts",
  "design",
  "graphic design",
  "web design",
  "ux/ui design",
  "fashion design",
  "interior design",
  "industrial design",
  "game design",
  "animation",
  "architecture",
  "civil engineering",
  "mechanical engineering",
  "electrical engineering",
  "electronics engineering",
  "biomedical engineering",
  "chemical engineering",
  "environmental engineering",
  "aerospace engineering",
  "geotechnical engineering",
  "urban planning",
  "law",
  "international law",
  "business law",
  "criminal law",
  "intellectual property law",
  "medicine",
  "nursing",
  "pharmacy",
  "dentistry",
  "veterinary science",
  "biotechnology",
  "genetics",
  "environmental science",
  "marine biology",
  "psychology",
  "counseling psychology",
  "educational psychology",
  "sociology",
  "political science",
  "international relations",
  "public administration",
  "linguistics",
  "education",
  "early childhood education",
  "special education",
  "physical education",
];

export default MAJORS;
