const ORGANIZATIONS = [
  "amazon web services (aws)",
  "microsoft",
  "google",
  "cisco systems",
  "red hat",
  "isc2 (international information system security certification consortium)",
  "adobe",
  "facebook",
  "isaca",
  "oracle university",
  "linux professional institute (lpi)",
  "the open group",
  "agile alliance",
  "scrum alliance",
  "itil (axelos)",
  "kubernetes (cncf - cloud native computing foundation)",
  "offensive security",
  "python institute",
  "ieee (institute of electrical and electronics engineers)",
  "acm (association for computing machinery)",
  "w3c (world wide web consortium)",

  "cfa institute",
  "aicpa (american institute of certified public accountants)",
  "gfa (global financial association)",
  "ifac (international federation of accountants)",
  "prmia (professional risk managers' international association)",
  "garp (global association of risk professionals)",
  "wharton school of the university of pennsylvania",
  "project management & business",
  "project management institute (pmi)",
  "axelos (prince2)",
  "six sigma institute",
  "iiba (international institute of business analysis)",
  "lean six sigma academy",

  "google digital garage",
  "facebook blueprint",
  "hubspot academy",
  "digital marketing institute (dmi)",
  "american marketing association (ama)",

  "national association of realtors (nar)",
  "institute of real estate management (irem)",

  "society for human resource management (shrm)",
  "human resources certification institute (hrci)",

  "american heart association (aha)",
  "national council of state boards of nursing (ncsbn)",
  "american nurses credentialing center (ancc)",
  "board of certified safety professionals (bcsp)",
  "language certifications",
  "british council",
  "ets (educational testing service)",
  "jlpt (japanese language proficiency test - japan foundation)",
  "topik (test of proficiency in korean - national institute for international education)",
  "alliance française",
  "goethe-institut",
];

export default ORGANIZATIONS;
