const POSITIONS = [
  "software engineer",
  "software developer",
  "senior software engineer",
  "software architect",

  "cloud architect",
  "cloud solutions consultant",
  "data analyst",
  "senior data engineer",
  "ux designer",
  "senior ux researcher",
  "senior financial analyst",

  "backend architect",
  "cybersecurity engineer",
  "senior data scientist",
  "senior blockchain developer",
  "ux/ui designer",
  "senior network engineer",
  "senior data analyst",
  "junior software engineer",
  "project manager",

  "backend developer",
  "frontend developer",
  "full stack developer",
  "mobile developer",
  "ai engineer",
  "machine learning engineer",
  "data scientist",
  "data engineer",
  "big data analyst",
  "cloud engineer",
  "devops engineer",
  "site reliability engineer (sre)",
  "cyber security analyst",
  "ethical hacker",
  "penetration tester",
  "system administrator",
  "database administrator",
  "network engineer",
  "blockchain developer",
  "game developer",
  "software tester",
  "qa engineer",
  "it support specialist",
  "business analyst (it)",
  "ui/ux designer",
  "product manager (it)",
  "senior graphic designer",
  "visual design lead",
  "senior ai engineer",
  "ai researcher",
  "cybersecurity specialist",
  "senior security consultant",

  "financial analyst",
  "investment manager",
  "portfolio manager",
  "risk manager",
  "credit analyst",
  "accountant",
  "auditor",
  "tax consultant",
  "chief financial officer (cfo)",
  "bank manager",
  "loan officer",
  "wealth manager",
  "financial planner",

  "business development manager",
  "sales manager",
  "marketing manager",
  "digital marketing specialist",
  "seo specialist",
  "customer relationship manager",
  "supply chain manager",
  "logistics coordinator",
  "operations manager",
  "human resource manager",
  "recruitment specialist",

  "civil engineer",
  "mechanical engineer",
  "electrical engineer",
  "biomedical engineer",
  "aerospace engineer",
  "chemical engineer",
  "environmental engineer",

  "graphic designer",
  "motion graphics designer",
  "web designer",
  "industrial designer",
  "game designer",
  "fashion designer",
  "interior designer",
  "art director",

  "doctor",
  "nurse",
  "pharmacist",
  "dentist",
  "veterinarian",
  "medical researcher",
  "physical therapist",

  "lawyer",
  "legal consultant",
  "judge",
  "government officer",
  "public policy analyst",

  "teacher",
  "lecturer",
  "academic researcher",
  "education consultant",
];

export default POSITIONS;
