const SCHOOLS = [
  "vietnam national university hanoi (vnu hanoi)",
  "ho chi minh city university of science and technology (hcmut)",
  "hanoi university of science and technology (hust)",
  "vietnam national university da nang (vnu da nang)",
  "national economics university (neu)",
  "foreign trade university (ftu)",
  "post and telecommunications institute of technology (ptit)",
  "academy of finance (aof)",
  "banking academy",
  "university of languages and international studies - vietnam national university hanoi (ulis)",
  "hanoi medical university",
  "fpt university hanoi",
  "thang long university",
  "hanoi university",
  "hanoi university of mining and geology",
  "hanoi university of agriculture",
  "hanoi university of industry",
  "hanoi national university of education",
  "university of transport and communications",
  "hanoi open university",
  "thuongmai university",
  "vietnam university of commerce",
  "vietnam national university da nang (vnu danang)",
  "da nang university of science and technology (dut)",
  "hue university",
  "quy nhon university",
  "nha trang university",
  "phan thiet university",
  "da nang university of economics",
  "da nang university of foreign language studies",
  "hue university of medicine and pharmacy",
  "hue university of agriculture and forestry",
  "hue university of economics",
  "hue university of sciences",
  "phu yen university",
  "ha tinh university",
  "university of nha trang fisheries",
  "university of pedagogy - da nang",
  "nghe an university of economics",
  "quang binh university",
  "quang nam university",
  "dong a university da nang",
  "vietnam national university ho chi minh city (vnu hcm)",
  "ho chi minh city university of technology (hcmut)",
  "university of information technology (uit)",
  "ho chi minh city university of science (hcmus)",
  "ton duc thang university (tdtu)",
  "fpt university ho chi minh city",
  "ho chi minh city university of education",
  "ho chi minh city university of law",
  "ho chi minh city university of transport",
  "ho chi minh city university of industry (iuh)",
  "ho chi minh city university of technology and education (hcmute)",
  "ho chi minh city university of foreign languages and information technology (huflit)",
  "foreign trade university ho chi minh city (ftu hcmc)",
  "rmit university vietnam (rmit)",
  "ho chi minh city university of architecture (hcmuac)",
  "ho chi minh city university of fine arts (hcmufa)",
  "rmit university vietnam (rmit)",
  "saigon university (sgu)",
  "van lang university (vlu)",
  "ho chi minh city open university",
  "nguyen tat thanh university (nttu)",
  "hoa sen university (hsu)",
  "hong bang international university (hiu)",
  "bach khoa aptech ho chi minh city",
  "vietnam-germany university (vgu)",
  "truong dai hoc su pham ky thuat vinh long",
  "can tho university (ctu)",
  "tra vinh university (tvu)",
  "dong nai technology university (dntu)",
  "massachusetts institute of technology (mit)",
  "harvard university",
  "stanford university",
  "university of oxford",
  "university of cambridge",
  "university of melbourne",
  "national university of singapore (nus)",
  "nanyang technological university (ntu)",
  "university of toronto",
  "university of sydney",
  "university of british columbia (ubc)",
  "university of new south wales (unsw)",
  "university of queensland",
  "peking university",
  "tsinghua university",
  "kyoto university",
  "seoul national university (snu)",
  "kaist (korea advanced institute of science and technology)",
  "hong kong university of science and technology (hkust)",
  "columbia university",
];

export default SCHOOLS;
