import "@stream-io/video-react-sdk/dist/css/styles.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { Mulish } from "next/font/google";
import "react-datepicker/dist/react-datepicker.css";

import "./globals.css";

import { Toaster } from "@/components/ui/toaster";
import AppProvider from "@/providers/app.provider";
import StreamClientProvider from "@/providers/stream-client.provider";
import ThemeProvider from "@/providers/theme-provider";

const fontFamily = Mulish({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "BK Sharing",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo-icon.png",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html
      lang={locale}
      className={fontFamily.className}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <AppProvider>
            <NextIntlClientProvider messages={messages}>
              <StreamClientProvider>{children}</StreamClientProvider>
            </NextIntlClientProvider>
          </AppProvider>
          <Toaster />
        </ThemeProvider>

        <SpeedInsights />
      </body>
    </html>
  );
}
